name: Docs
on: 
  push:
    branches:
      - 'feature/**'

permissions:
    contents: write

jobs:
  docs:
    runs-on: [self-hosted, server]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Install docs dependencies
        run: |
          source venv/bin/activate
          pip install -r ./docs/requirements.txt
      - name: Sphinx build
        run: |
          source venv/bin/activate
          sphinx-build ./docs/source _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/feature/**' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true