name: Yolo Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - 'feature/**'

jobs:
  yolo_unit_tests:
    runs-on: [self-hosted, server]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Install pytorch
        run: |
          pip3 install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
      - name: Run python unit tests
        run: venv/bin/python -m unittest discover -s test
